import type { ColumnType } from '../../../types';

export const COLLAPSED_STRIP_HEIGHT = 28;

export const columnTypeClasses: Record<ColumnType, string> = {
  Text: 'bg-blue-500',
  LongText: 'bg-blue-500',
  Show: 'bg-blue-500',
  Name: 'bg-blue-500',
  App: 'bg-blue-500',
  Number: 'bg-emerald-500',
  Decimal: 'bg-emerald-500',
  Percent: 'bg-emerald-500',
  Price: 'bg-emerald-500',
  Date: 'bg-amber-500',
  DateTime: 'bg-amber-500',
  Time: 'bg-amber-500',
  Duration: 'bg-amber-500',
  Email: 'bg-violet-500',
  Phone: 'bg-violet-500',
  Url: 'bg-violet-500',
  Image: 'bg-pink-500',
  Thumbnail: 'bg-pink-500',
  Video: 'bg-pink-500',
  File: 'bg-pink-500',
  Drawing: 'bg-pink-500',
  Signature: 'bg-pink-500',
  Enum: 'bg-indigo-500',
  EnumList: 'bg-indigo-500',
  'Yes/No': 'bg-red-500',
  Color: 'bg-orange-500',
  LatLong: 'bg-teal-500',
  XY: 'bg-teal-500',
  Address: 'bg-teal-500',
  Ref: 'bg-cyan-500',
  ChangeCounter: 'bg-slate-500',
  ChangeLocation: 'bg-slate-500',
  ChangeTimestamp: 'bg-slate-500',
  Progress: 'bg-green-500',
  UniqueID: 'bg-purple-500',
};
